function [thrPref] = cfgData_createThrPref
% function to create default settings for threshold preferences
%
% - ignZero:      whether zeros should be ignored (true) or not (false)
% - transparency: overall opacity of data overlay
% - numCmaps:     number of color maps, either 1 or 2 (if using -ve)
% - cmapNames:    names for color map(s)
% - cmapVals:     min/max for color map(s)
%                 order: [cMin1, cMax1; cMin2, cMax2]
% - outlierMode:  either 'map' or 'clip' values outside color range
% - useSig:       if data has sig. values attached, whether to use it
% - useLog:       use log10(x) for thresholding/thr. graph/stats graph 
%                 respectively
% - thrCode:      code (1:12) indicating type of thresholding to use
% - thrVals:      values representing the limits of the threshold
%                 order: [a1, a2; b1, b2]
% - thrXLim:      x-axis limits for the threshold preview
% - histXLim:     x-axis limits for the histogram
%                 order: [data(min), data(max); sig(min), sig(max)]
% - histNBins:    number of bins for the histogram

thrPref = struct(...
    'ignZero',      true,...
    'transparency', 1,...
    'numCmaps',     uint8(1),...
    'cmapNames',    {{'heat';'cool'}},...
    'cmapVals',     nan(2,2),...
    'outlierMode',  'map',...
    'useSig',       false,...
    'useLog',       false(3,1),...
    'thrCode',      ones(3,1),...
    'thrVals',      nan(2,2),...
    'thrXLim',      nan(2,1,'single'),...
    'histXLim',     nan(2,2,'single'),...
    'histNBins',    nan(2,1,'single')...
    );

end