function calcCentroid(obj)
% function to calculate the centroid of a volume
%
% (set.) centroid, centroid of the volume

% split the volume into tetrahedrons (pyramids)
T = uint32(delaunay(obj.TR.Points));

% calculate centroids of each tetrahedron
centroids = [...
    mean(reshape(obj.TR.Points(T(:),1),size(T)),2),...
    mean(reshape(obj.TR.Points(T(:),2),size(T)),2),...
    mean(reshape(obj.TR.Points(T(:),3),size(T)),2)...
    ];

% calculate volumes of each tetrahedron
vols = abs(dot(...
    bsxfun(@minus,obj.TR.Points(T(:,1),:),obj.TR.Points(T(:,4),:)),...
    cross(....
    bsxfun(@minus,obj.TR.Points(T(:,2),:),obj.TR.Points(T(:,4),:)),...
    bsxfun(@minus,obj.TR.Points(T(:,3),:),obj.TR.Points(T(:,4),:))...
    ,2),2))/6;

% centroid is volume weighted sum of tetrahedroin centroids
obj.centroid = sum(centroids.*vols)./sum(vols);

end